### ISSUE TITLE
How can we access the fastify instance in a route handler?

### ISSUE THREAD

**Issue by cmmartin** [spa5k/fastify-file-routes#30]

**Comment by spa5k** [comment]
Don't think it's a possibility unless you export and import it some way

**Comment by cmmartin** [comment]
Would be awesome to support something like...

```typescript
const route = (fastify: FastifyInstance) => ({
   handler: async (_res, reply) => {
     reply.send(await fastify.db.query('select * from users'))
   }
})
```

**Comment by spa5k** [comment]
This module has been pending a full rewrite but I haven't been able to make anytime for it, if I do, I'll add this feature.

**Comment by cmmartin** [comment]
I can't test this at the moment, but I just realized that the following should work...

```typescript
export const route: Route = {
   handler: async function (_res, reply) {
     reply.send(await this.db.query('select * from users'))
   }
}
```

As long as you don't use an arrow function, I believe fastify will bind the instance to `this` in your handler function. From their [docs](https://www.fastify.io/docs/latest/Reference/Routes/)...

> The Fastify server will be bound to this when the handler is called. Note: using an arrow function will break the binding of this.

**Comment by spa5k** [comment]
oh yeah, we had this functionality in fastify-slonik iirc
